language: ruby
cache: bundler


rvm:
  - jruby
  - 2.0.0

script: 'bundle exec rake'
notifications:
  email:
    recipients:
      - xhan610@gmail.com
      on_failure: change
      on_success: never

